version: '3.1'
services:
  eclipse: 
    image: eclipse:${BUILDTAG}
    build:
      context: .
      dockerfile: ops/Dockerfile
      args:
        ideDir: ./eclipse/
        jdkDir: ./jdk/
        UID: ${UID}
        GID: ${GID}
    environment:
      UID: ${UID}
      GID: ${GID}
    env_file:
        - .env
    volumes:
      - ./eclipse:/java/ide
      - ./jdk:/java/jdk
      - ./workspace:/java/workspace
      - ./developer:/home/developer/
      - /tmp/.X11-unix:/tmp/.X11-unix

