version: '3.1'
services:
  ide: 
    image: intellij_ce:stable
    devices:
      - /dev/video0:/dev/video0
    extra_hosts:
      - "pulse.server:host-gateway"
    volumes:
      - /run/udev/data:/run/udev/data:ro
      # - ./${DOCKER_USER}/IdeaProjects:/home/${DOCKER_USER}/IdeaProjects
      # - ./${DOCKER_USER}/jdks:/home/${DOCKER_USER}/.jdks
      # - ./${DOCKER_USER}/code_extensions:/home/${DOCKER_USER}/.vscode/extensions/
      # - ./${DOCKER_USER}/${AWS_CREDENTIALS_LOCAL_DIR}:/home/${DOCKER_USER}/.aws
      # - ./${DOCKER_USER}/${AWS_SAM_CREDENTIALS_LOCAL_DIR}:/home/${DOCKER_USER}/.aws_sam
      # - ./${DOCKER_USER}/${GOOGLE_CREDENTIALS_LOCAL_DIR}:/home/${DOCKER_USER}/.google
    ports:
      - 3389:3389 #xrdp
      - 3350:3350 #xrdp-sesman
      - 8081:8080
      - 8181:8181

